package cn.leo.base.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.leo.base.db.bean.UserDetailInfo;

import cn.leo.base.db.UserDetailInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDetailInfoDaoConfig;

    private final UserDetailInfoDao userDetailInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDetailInfoDaoConfig = daoConfigMap.get(UserDetailInfoDao.class).clone();
        userDetailInfoDaoConfig.initIdentityScope(type);

        userDetailInfoDao = new UserDetailInfoDao(userDetailInfoDaoConfig, this);

        registerDao(UserDetailInfo.class, userDetailInfoDao);
    }
    
    public void clear() {
        userDetailInfoDaoConfig.clearIdentityScope();
    }

    public UserDetailInfoDao getUserDetailInfoDao() {
        return userDetailInfoDao;
    }

}
